name: baschack
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.0.0
  dbcrypt: ^2.0.0
  dio: ^4.0.6
  jaguar_jwt: ^3.0.0
  mailer: ^5.1.1
  random_string: ^2.3.1

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
